### ISSUE TITLE
Access to the Opta Playground XML data?

### ISSUE THREAD

**Issue by aqsmith08** [jokecamp/jokecamp.com#3]
Hi Joe,

In this [blog post](http://www.jokecamp.com/blog/guide-to-football-and-soccer-data-and-apis/), you mention --

"*I applied and they sent me the xml data set for 10 rounds of games from the start of the 2007/2008 Bundesliga 2. The more detailed game data had either x,y coordinates of game events. A very impressive dataset but it felt more like an advertisement. The data provided I had no interest in and I'm not sure why an indie developer would spend time working on a data set they could never afford.*"

I'm curious if you've uploaded the data to Github (or somewhere else)? Is there a way for me to access it?

Thanks,
Aaron

**Comment by jokecamp** [comment]
Hey Aaron, can you reach out to me via email at jokecamp@gmail.com

**Comment by jokecamp** [comment]
Sorry guys but I no longer have these data files since I forgot to save them at the time.
